---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readxl)
```

```{r}
df <- read_excel("/Users/counterpartventures/Desktop/Data/Survey_Data_V3.21.xlsx", 
                     sheet = "Master Data")

csuite <- read_excel("/Users/counterpartventures/Desktop/Data/csuite_changes.xlsx", sheet = "Sheet1")

csuite_v2 <- read_excel("/Users/counterpartventures/Desktop/Data/csuite_changes_v2.xlsx", sheet = "Leaders List")
```

```{r}
changes <- csuite %>%
  select(`Company Name`, Name, `Start Date`, Status, `Full Title`) %>%
  arrange(`Company Name`,`Start Date`) %>% 
  filter(`Start Date` > as.POSIXct("2020-01-01"))

changes_v2 <- csuite_v2 %>%
  select(`Company Name`, Name, `Start Date`, Status, `Full Title`) %>%
  arrange(`Company Name`,`Start Date`) %>%
  filter(`Start Date` > as.POSIXct("2020-01-01"))
```

```{r}
corps_with_changes <- changes %>%
  group_by(`Company Name`) %>%
  filter(n() > 1) %>%
  filter(n_distinct(`Start Date`) > 1)


corps_with_changes_2 <- changes_v2 %>%
  group_by(`Company Name`) %>%
  filter(n() > 1) %>%
  filter(n_distinct(`Start Date`) > 1)
  
```

```{r}
four_years <- df %>%
  filter(survey_count == 4)
```

# look at changes in investment allocation
```{r}
invest_allocation <- df %>%
  select(invest_allocation_per_annum_from_23, invest_allocation_per_annum_from_24) %>%
  na.omit()

changes_24_to_23 <- invest_allocation$invest_allocation_per_annum_from_24 -
  invest_allocation$invest_allocation_per_annum_from_23

changes_24_to_23

hist(changes_24_to_23, breaks=seq(-150, 200, by=10))
```

