---
title: "R Notebook"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(areaplot)
library(readxl)
library(stringr)
```


```{r}
df <- read_excel("/Users/counterpartventures/Desktop/Data/Survey_Data_V3.22.xlsx", 
                     sheet = "Master Data")
```

```{r}
delimiters <- c("; ", "\r\n", "#")

contains_any_char <- function(column, chars) {
  any(sapply(chars, function(char) any(str_detect(column, char))))
}

mult_response <- df %>%
  select_if(~contains_any_char(.,delimiters))


```

```{r}
library(dplyr)
questions <- colnames(mult_response)
years <- str_sub(questions, -2, -1)
years <- paste(20, years, sep = "")
questions_only <- substr(questions, 1, nchar(questions) - 8)

q_df <- data.frame(
  question = questions_only,
  years_asked = years
) 

unique_questions <- q_df %>%
  group_by(question) %>%
  summarise(years = paste(years_asked, collapse = ", ")) %>%
  ungroup()
```


```{r}
write.xlsx(unique_questions, "/Users/counterpartventures/Desktop/Data/subsets/multiple_response_qs.xlsx")

write.xlsx(unique_questions, "/Users/counterpartventures/Desktop/Data/subsets/multiple_response_qs_long.xlsx")
```

# set wd

```{r}
getwd()
setwd("Users/counterpartventures/Desktop/Data/subsets")
```


# Industries Invested

```{r}
industries_invested <- df %>%
  select(cvc_name, industries_invested_from_24) %>%
  separate_rows(industries_invested_from_24, sep = "\r\n") %>%
  mutate(year = rep(24, nrow(industries_invested)))

write.xlsx(industries_invested, "/Users/counterpartventures/Desktop/Data/subsets/industries_invested.xlsx")
```

# CVC Goals
```{r}
goals <- df %>%
  select(cvc_name, strat_execsponsor_goal_from_21, strat_execsponsor_goal_from_22, 
         strat_execsponsor_goal_from_23, strat_execsponsor_goal_from_24) %>%
  pivot_longer(cols = starts_with("strat_execsponsor_goal"), 
               names_to = "year", values_to = "strat_execsponsor_goal") %>%
  mutate(year = as.numeric(substr(year, nchar(year)-1, nchar(year)))) %>%
  mutate(year = as.numeric(paste0("20", year))) %>%
  separate_rows(strat_execsponsor_goal, sep = "; |#|\r\n") 
  

write.xlsx(goals, "/Users/counterpartventures/Desktop/Data/subsets/goals.xlsx")
```

## for long 
```{r}
goals_long <- df %>%
  select(cvc_name, strat_execsponsor_goal_from_21, strat_execsponsor_goal_from_22, 
         strat_execsponsor_goal_from_23, strat_execsponsor_goal_from_24) %>%
  pivot_longer(cols = starts_with("strat_execsponsor_goal"), 
               names_to = "year", values_to = "strat_execsponsor_goal") %>%
  mutate(year = as.numeric(substr(year, nchar(year)-1, nchar(year)))) %>%
  mutate(year = as.numeric(paste0("20", year))) %>%
  separate_rows(strat_execsponsor_goal, sep = "; |#|\r\n") 
  
```

```{r}
library(openxlsx)
workbook <- loadWorkbook("/Users/counterpartventures/Desktop/Data/subsets/questions_mult_responses.xlsx")
```

# Takes LP
```{r}
lp <- df %>%
  select(cvc_name, takes_lp_positions_from_21, takes_lp_positions_from_22, 
         takes_lp_positions_from_23, takes_lp_positions_from_24) %>%
  separate_rows(takes_lp_positions_from_21, sep = "; ") %>%
  separate_rows(takes_lp_positions_from_22, sep = "#") %>%
  separate_rows(takes_lp_positions_from_23, sep = "\r\n") %>%
  separate_rows(takes_lp_positions_from_2, sep = "\r\n")

addWorksheet(workbook, "takes_lp")
writeData(workbook, sheet = "takes_lp", x = lp)
saveWorkbook(workbook,"/Users/counterpartventures/Desktop/Data/subsets/questions_mult_responses.xlsx", overwrite = TRUE)
```

# Fund Source
```{r}



```



